# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(9, 94, 60, 16))
        self.label_result.setObjectName("label_result")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(270, 94, 16, 16))
        self.result.setObjectName("result")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 82, 16))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.height = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(139, 9, 49, 23))
        self.height.setMaximum(2.0)
        self.height.setSingleStep(0.01)
        self.height.setObjectName("height")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(9, 38, 67, 16))
        self.label_2.setObjectName("label_2")
        self.weight = QtWidgets.QSpinBox(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(139, 38, 45, 23))
        self.weight.setMaximum(200)
        self.weight.setObjectName("weight")
        self.calculat = QtWidgets.QPushButton(self.centralwidget)
        self.calculat.setGeometry(QtCore.QRect(139, 67, 84, 21))
        self.calculat.setObjectName("calculat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 403, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_result.setText(_translate("MainWindow", "Dein BMI ist:"))
        self.result.setText(_translate("MainWindow", "00"))
        self.label.setText(_translate("MainWindow", "K&ouml;pergr&ouml;&szlig;e in m:"))
        self.label_2.setText(_translate("MainWindow", "Gewicht in kg:"))
        self.calculat.setText(_translate("MainWindow", "BMI Berechnen!"))
